# Copied from docker-python tutorial 
# References: https://docs.docker.com/engine/reference/builder/
# syntax=docker/dockerfile:1

# Specifies the base image we're extending.
ARG PYTHON_VERSION=3.11
FROM python:${PYTHON_VERSION}-slim as base

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

# Downloads dependencies as a separate step to take advantage of Docker's caching.

# Leverages a cache mount to /root/.cache/pip to speed up subsequent builds.
# Leverages a bind mount to requirements.txt to avoid having to copy them into
# into this layer.

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    python -m pip install -r requirements.txt


# Copies the source code into the container.
COPY node1.py .

# Exposes the port that the application listens on.
EXPOSE 5001

# Runs the application.
CMD python3 -m flask run --host=172.28.0.0